[package]
name = "rusty-wit-gui"
version = "0.1.0"
authors = ["Manuel Quarneti <hi@mq1.eu>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
anyhow = "1.0"
rfd = "0.11"
ureq = "2.6"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
plist = "1"
sysinfo = "0.28"

[build-dependencies]
slint-build = "1.0"
